### GET token from Auth0

curl --request POST \
  --url https://dev-wc0lfyz5dygcms0y.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"2RU8YYsEIXAsD0nU0jvdFjgJC30DOhne","client_secret":"JLUgnD0PavdG9wczk8LFvc4LbGWwmYybAyHcpWVvdbIzyugBdKtfbSTV_5NXduU7","audience":"https://decisive-wizard","grant_type":"client_credentials"}'

### DELETE an Item to the Catalog collection
curl --response DELETE \
    --url https://localhost:7250/catalog/3 \
    --header 'authorization: Bearer {eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRFZU1RS0lQb0NrNEpjT3NzUnZqYSJ9.eyJpc3MiOiJodHRwczovL2Rldi13YzBsZnl6NWR5Z2NtczB5LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiIyUlU4WVlzRUlYQXNEMG5VMGp2ZEZqZ0pDMzBET2huZUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9kZWNpc2l2ZS13aXphcmQiLCJpYXQiOjE2ODIzODQ4MjYsImV4cCI6MTY4MjQ3MTIyNiwiYXpwIjoiMlJVOFlZc0VJWEFzRDBuVTBqdmRGamdKQzMwRE9obmUiLCJzY29wZSI6ImRlbGV0ZTpjYXRhbG9nIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.MWIJofbp4CEmN9RRPyWqKMA-lYX_n0SEszcEnHBix6Cian3NoSyxOun7elDVDUqn38XHdG8PCOWTPLBITuCylWuZXbVcVYGC_ReUaqv76JZW2VOrrp5Z1fEXsLSw98oAW-Ms8cB9Co1uDam_JOw6U059vHVr7GWtGyiIEGTzFmqbnZtfUGEr3hxPXHiMHJS3DNt9akI2p05Ql5iCOT9KWRCdMhbVrPNLWalm2_IcjrzViD6hww3IyK2wOoGXtNPoLPVTjURx5ccgKo61snDRYB3i0eDXrZG7LyqALw8tdEXlCIhOVmUcn374b6p051V3UN4rl2jiWCHi5E2wEsTCZw}'
